### PR TITLE
Fix bugs with checking level and compile icons

### LINKED ISSUE #633: Fix bug with checking level and chapter compile
Checking level is not registered correctly on the chapter card. Dialog shows up, but when user clicks "OK", it doesn't save/persist.

Compile icon opens up the dialog. But when clicked for the first time (not a re-compile), the compile process is executed without user's confirmation on the dialog.

### PR DESCRIPTION
**Pull request by vleong2332**
Should resolve #633

### CODE REVIEW

File: RecordingApp/app/src/main/java/wycliffeassociates/recordingapp/ProjectManager/CompileDialog.java [hunk 1]
```diff
@@ -60,9 +60,11 @@ public void onCreate(Bundle savedInstanceState) {
...
-            mListener.onPositiveClick(CompileDialog.this);
-        }
+        // NOTE: This is commented out because we don't want the compile to execute without the user
+        //    clicking "OK" on the dialog. If Joe agrees, he can delete this.
+        // if(!mAlreadyCompiled){
+        //     mListener.onPositiveClick(CompileDialog.this);
+        // }
         return new AlertDialog.Builder(getActivity())
             .setTitle("Warning")
             .setMessage("Re-compiling a chapter will over-write the current audio and reset the checking level.")
```
Comment (jsarabia1247) [inline RecordingApp/app/src/main/java/wycliffeassociates/recordingapp/ProjectManager/CompileDialog.java]: With the above code commented out, chapters that have not been compiled give a warning about what happens on recompile. Is this appropriate? Would it cause confusion for the user?

Comment (vleong2332) [inline RecordingApp/app/src/main/java/wycliffeassociates/recordingapp/ProjectManager/CompileDialog.java]: We'll revert to the original plan of only showing the dialog on re-compile, not for the first time.
